# Numpy

NumPy is the fundamental package for scientific computing in Python, it is a Python library that provides a multidimensional array object, and has diverse functions for manipulation, transformation and data analysis.

In [ ]:
# The way numpy is imported
import numpy as np

### Array

The basic component of numpy is the **array**  
Array: is a grid of values, all of the same type, and is indexed by a tuple of nonnegative integers.

In [11]:
#To create an array, first we have to establish a set of data
import numpy as np
list1 = [1,2,3,4,5]
list1 = np.array(list1)

print(type(list1))
print(list1)


<class 'numpy.ndarray'>
[1 2 3 4 5]
1


The example above, was an array of 1 dimension, we can use 2 or even 3 dimensions.  
In mathematics it is called a matrix

In [10]:
import numpy as np

# 1 dimension array
list1 = [1,2,3,4,5]
list1 = np.array(list1)

print(list1)

# 2 dimension array
list2 = [[1,2,3], [4,5,6], [7,8,9]]
list2 = np.array(list2)
print(list2)

[1 2 3 4 5]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


The numpy arrays are indexed, that means they follow an order, and it can be iterated trough

In [25]:
import numpy as np

list1 = [1,2,3,4,5]
list1 = np.array(list1)

#The position 0 is the first position in an indexed set of data
print(list1[0])
print(list1[0:2])

1
[1 2]


In [37]:
#You can also acces the index position in a matrix
list1 = [[1,2,3], [4,5,6], [7,8,9]]
list1 = np.array(list2)

#Accesing the first row
print(list1[0])

#Acessing the second row
print(list1[1])

#Acessing the Third row
print(list1[2])

#Acessing the first row, first column
print(list1[0,0])

#Acessing the second row, second column
print(list1[1,1])

#Acessing the third row, third column
print(list1[2,2])


[1 2 3]
[4 5 6]
[7 8 9]
1
5
9


In [40]:
#You can do operations with this indices
list1 = [1,2,3,4,5]

print(list1[0] + list1[1])

print(list1[4] - list1[1])

print(list1[0] * list1[1])

print(list1[4] / list1[1])

#Operations with matrices
list2 = [
    [1,2,3],
    [4,5,6],
    [7,8,9]
]
list2 = np.array(list2)

print(list2[0] * list2[1])
print(list2[0] * list2[0])






3
3
2
2.5
[ 4 10 18]
[1 4 9]


### Data types

In [56]:
import numpy as np

list1 = [12,34,15,9,3]
list1 = np.array(list1)

#The printed array is an integer
print(list1.dtype)
print(list1)

#Then transformed into boolean
list1 = list1.astype(np.bool_)
print(list1.dtype)
print(list1)

#Then transformed into float
list1 = list1.astype(np.float_)
print(list1.dtype)
print(list1)

#Then transformed into string
list1 = list1.astype(np.string_)
print(list1.dtype)
print(list1)



int64
[12 34 15  9  3]
bool
[ True  True  True  True  True]
float64
[1. 1. 1. 1. 1.]
|S32
[b'1.0' b'1.0' b'1.0' b'1.0' b'1.0']


### Dimensions

The arrays can have multiple dimensions, and tehir names are
* Scalar: No dimensions, just a single data
* Vector: 1 Dimensions, a single row of data
* Matrix: 2 Dimensions
* Matrix: 3 Dimensions
* Tensor. 4 or more Dimensions

In [13]:
#Examples of dimensions
import numpy as np

# 0 Dimensions, a single data
scalar = np.array(5)
print(scalar)
print("This array has", scalar.ndim, "dimensions")

# 1 dimensions
vector = [2,3,5,7]
vector = np.array(vector)
print(vector)
print("This array has", vector.ndim, "dimensions")

# 2 Dimensions
matrix = [
    [0,1,1],
    [2,3,5],
    [8,13,21]
]

matrix = np.array(matrix)

print(matrix)
print("This array has", matrix.ndim, "dimensions")

#3 Dimenions

matrix2 = [
    [
        [1,2,3],
        [4,5,6],
        [7,8,9]
    ],
    [
        [10,11,12],
        [13,14,15],
        [16,17,18]
    ]
]

matrix2 = np.array(matrix2)

print(matrix2)
print("This array has", matrix2.ndim, "dimensions")

# 4 Dimensions
tensor = [
    [
        [
            [1,2,3],
            [4,5,6]
        ],
        [
            [7,8,9],
            [10,11,12]
        ]
    ],
    [
        [
            [13,14,15],
            [16,17,18]
        ],
        [
            [19,20,21],
            [22,23,24]
        ]
    ]
]

tensor = np.array(tensor)
print(tensor)
print("This array has", tensor.ndim, "dimensions")

5
This array has 0 dimensions
[2 3 5 7]
This array has 1 dimensions
[[ 0  1  1]
 [ 2  3  5]
 [ 8 13 21]]
This array has 2 dimensions
[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]]
This array has 3 dimensions
[[[[ 1  2  3]
   [ 4  5  6]]

  [[ 7  8  9]
   [10 11 12]]]


 [[[13 14 15]
   [16 17 18]]

  [[19 20 21]
   [22 23 24]]]]
This array has 4 dimensions


Establishing, adding, and deleting dimensions

In [22]:
#To format an arraay with an specific number of dimensions
array1 = np.array([5,6,7], ndmin=3)
print(array1)
print(array1.ndim)

#To add a dimension
array2 = np.expand_dims([9,8,7], axis=0)
print(array2)
print(array2.ndim)

#To fit the dimensions to the existing data
array3 = np.squeeze(array1)
print(array3)
print(array3.ndim)


[[[5 6 7]]]
3
[[9 8 7]]
2
[5 6 7]
1


Shape

In [43]:
import numpy as np

#Establishing a random array, with the range from 1 to 10, with 2 dimensions, with the shape of 3,3
arr1 = np.random.uniform(1,10, (3,3))
arr1 = np.round_(arr1, decimals = 2)
print(arr1)
print("The shape of the array is", arr1.shape)

arr2 = np.random.uniform(1,20, (3,4))
arr2 = np.round_(arr2,decimals=2)
print(arr2)
print("The shape of the array is", arr2.shape)

#Reshaping arr2
arr2 = arr2.reshape(1,12)
print(arr2)
print("The shape of the array is", arr2.shape)

arr2 = arr2.reshape(2,6)
print(arr2)
print("The shape of the array is", arr2.shape)

#There are 2 ways to reshape, the C way, and the Fortrand way, and we can establish those ways
arr2 = np.reshape(arr2,(3,4), "C")
print(arr2)
print("The shape of the array is", arr2.shape)

arr2 = np.reshape(arr2,(3,4), "F")
print(arr2)
print("The shape of the array is", arr2.shape)

arr2 = np.reshape(arr2,(3,4), "A")
print(arr2)
print("The shape of the array is", arr2.shape)



[[2.05 2.46 1.44]
 [1.88 1.81 5.53]
 [5.26 2.12 3.68]]
The shape of the array is (3, 3)
[[ 1.31  5.67  1.81  8.18]
 [15.3  16.64 17.99  5.53]
 [10.7  17.08  8.93 12.71]]
The shape of the array is (3, 4)
[[ 1.31  5.67  1.81  8.18 15.3  16.64 17.99  5.53 10.7  17.08  8.93 12.71]]
The shape of the array is (1, 12)
[[ 1.31  5.67  1.81  8.18 15.3  16.64]
 [17.99  5.53 10.7  17.08  8.93 12.71]]
The shape of the array is (2, 6)
[[ 1.31  5.67  1.81  8.18]
 [15.3  16.64 17.99  5.53]
 [10.7  17.08  8.93 12.71]]
The shape of the array is (3, 4)
[[ 1.31  5.67  1.81  8.18]
 [15.3  16.64 17.99  5.53]
 [10.7  17.08  8.93 12.71]]
The shape of the array is (3, 4)
[[ 1.31  5.67  1.81  8.18]
 [15.3  16.64 17.99  5.53]
 [10.7  17.08  8.93 12.71]]
The shape of the array is (3, 4)


In [20]:
#Maximun and minimun
import numpy as np
import random

arr1 = np.random.randint(1,20,(2,5))
print(arr1)

#get max
print("The maximun value in the array is",arr1.max())

#get max by column and row
print("The maximun value in the array by column is", arr1.max(0))
print("The maximun value in the array by row is", arr1.max(1))

#the position of the max value in the index
print("The position of the maximun valie in the array is", arr1.argmax())

#get min
print("The minimun value in the array is",arr1.min())

#get min by column and row
print("The minimun value in the array by column is", arr1.min(0))
print("The minimun value in the array by row is", arr1.min(1))

#the position of the min value in the index
print("The position of the minimun value in the array is", arr1.argmin())

[[ 4 16  2  6  5]
 [12 12  7  1 18]]
The maximun value in the array is 18
The maximun value in the array by column is [12 16  7  6 18]
The maximun value in the array by row is [16 18]
The position of the maximun valie in the array is 9
The minimun value in the array is 1
The minimun value in the array by column is [ 4 12  2  1  5]
The minimun value in the array by row is [2 1]
The position of the minimun value in the array is 8


In [40]:
#Range function (called ptp, pick to pick)
import numpy as np

arr1 = np.random.randint(1,20,(3,4))
print(arr1)

#Range, difference between the max value and the min value
print("The range of the array is", arr1.ptp())

#Range in every column, and row
print("The range in every column is",arr1.ptp(0))
print("The range in every row is",arr1.ptp(1))

#We can apply a function that evokes the percentiles
print("The percentile 25 value of the array is",np.percentile(arr1,25))

#We can apply a function that sorts the values
print("The values sorted are", np.sort(arr1))
print("The values sorted trough columns are", np.sort(arr1,0))
print("The values sorted trough rows are", np.sort(arr1,1))

#Median function
print("The median of the array is", np.median(arr1))

#Mean function
print("The mean of the array is", np.round_(np.mean(arr1), decimals=2))

#The standard deviation
print("The standard deviation is", np.round_(np.std(arr1), decimals=2))

#Variance
print("The variance is", np.round_(np.var(arr1), decimals=2))

[[14 17  1 14]
 [ 5 18  4 14]
 [ 7  3 11  1]]
The range of the array is 17
The range in every column is [ 9 15 10 13]
The range in every row is [16 14 10]
The percentile 25 value of the array is 3.75
The values sorted are [[ 1 14 14 17]
 [ 4  5 14 18]
 [ 1  3  7 11]]
The values sorted trough columns are [[ 5  3  1  1]
 [ 7 17  4 14]
 [14 18 11 14]]
The values sorted trough rows are [[ 1 14 14 17]
 [ 4  5 14 18]
 [ 1  3  7 11]]
The median of the array is 9.0
The mean of the array is 9.08
The standard deviation is 6.01
The variance is 36.08


**Copy function**  
This function is fundamental because this allow us to leave the copy array unchanged. If we modified the copy array, that can be troubled because we can lose data

In [59]:
import numpy as np

arr1 = [1,2,3,4,5]
arr1 = np.array(arr1)
print("This is the original array", arr1)

arr2 = arr1[0:3]
print("This is a slice of the original array, we wanna acces",arr2)

arr2[:] = 0
print("This is the slice of the original array, modified", arr2)

print("If we try to access the original one, we can see it has been modified too", arr1)

arr3 = [1,2,3,4,5]
arr3 = np.array(arr3)
print("This is another original array", arr3)

arr4 = arr3.copy()
print("This is a copy of the original array", arr4)

print("Now we can modified the copied array without worries about losing data in the original one")

This is the original array [1 2 3 4 5]
This is a slice of the original array, we wanna acces [1 2 3]
This is the slice of the original array, modified [0 0 0]
If we try to access the original one, we can see it has been modified too [0 0 0 4 5]
This is another original array [1 2 3 4 5]
This is a copy of the original array [1 2 3 4 5]
Now we can modified the copied array without worries about losing data in the original one


### Numpy Conditionals  

Numpy allows you to apply conditional to the arrays

In [19]:
import numpy as np
arr1 = np.random.randint(1,100,(3,3))
print("These is the original array",arr1)

#When applying a conditional, numpy return you a boolean
print("Applying a conditional to return values greater than 20",arr1 > 20)

#Saving the conditional in a new array
great_20 = arr1 > 20
print(great_20)

#Two conditionals
print("This is an array with 2 conditionals applied",(arr1 > 20) & (arr1 < 80))

#Odd numbers conditional

print(arr1 % 2 != 0)



These is the original array [[86 42 99]
 [63 59 27]
 [51 58 37]]
Applying a conditional to return values greater than 20 [[ True  True  True]
 [ True  True  True]
 [ True  True  True]]
[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]
This is an array with 2 conditionals applied [[False  True False]
 [ True  True  True]
 [ True  True  True]]
[[False False  True]
 [ True  True  True]
 [ True False  True]]


Arithmetic Operations with numpy

In [11]:
#We can do the basic operation in an array
import numpy as np

arr1 = np.random.randint(1,10,(1,4))
print(arr1)

print("We can do sum", arr1 + 2)
print("We can do rest", arr1 - 5)
print("We can do multiplication", arr1 * 2)
print("We can do division", arr1 / 2)

#And we even can do operation between arrays itself

print("Sum of the same array", arr1 + arr1)

arr2 = np.random.randint(1,10,(3,4))
print("array 2", arr2)

arr3 = np.random.randint(1,10,(3,4))
print("Array 3", arr3)

#Multiplying arr2 and arr3
print("arr2 * arr3" ,arr2 * arr3)

[[3 1 6 8]]
We can do sum [[ 5  3  8 10]]
We can do rest [[-2 -4  1  3]]
We can do multiplication [[ 6  2 12 16]]
We can do division [[1.5 0.5 3.  4. ]]
Sum of the same array [[ 6  2 12 16]]
array 2 [[9 8 2 4]
 [4 2 1 4]
 [4 3 4 6]]
Array 3 [[5 7 8 5]
 [7 8 3 8]
 [8 5 9 3]]
arr2 * arr3 [[45 56 16 20]
 [28 16  3 32]
 [32 15 36 18]]


In [3]:
import numpy as np

x = np.empty(5)
print(x)

[1. 1. 1. 1. 1.]
